### ISSUE TITLE
failed due to unexpected error: SoftTimeLimitExceeded

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#146]
Fresh deployment w. vagrant, first experiment runs but produces an error message

```
failed due to unexpected error: SoftTimeLimitExceeded: SoftTimeLimitExceeded()
Full internal details follow:
Traceback (most recent call last):
File "/opt/celery/repo/fcws/tasks.py", line 287, in RunExperiment
r = Callback(callbackUrl, signature, {'returntype': outcome}, files=files)
File "/opt/celery/repo/fcws/tasks.py", line 47, in Callback
r = requests.post(callbackUrl, verify=False, **kwargs)
File "/opt/celery/venv/local/lib/python2.7/site-packages/requests/api.py", line 116, in post
return request('post', url, data=data, json=json, **kwargs)
File "/opt/celery/venv/local/lib/python2.7/site-packages/requests/api.py", line 60, in request
return session.request(method=method, url=url, **kwargs)
File "/opt/celery/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/opt/celery/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/opt/celery/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 449, in send
timeout=timeout
File "/opt/celery/venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/opt/celery/venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 377, in _make_request
httplib_response = conn.getresponse(buffering=True)
File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
response.begin()
File "/usr/lib/python2.7/httplib.py", line 453, in begin
version, status, reason = self._read_status()
File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
line = self.fp.readline(_MAXLINE + 1)
File "/usr/lib/python2.7/socket.py", line 480, in readline
data = self._sock.recv(self._rbufsize)
File "/opt/celery/venv/local/lib/python2.7/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
raise SoftTimeLimitExceeded()
SoftTimeLimitExceeded: SoftTimeLimitExceeded()
(backend returned no archive) 
```

![Screenshot from 2019-05-16 11-36-11](https://user-images.githubusercontent.com/517644/57847821-55a01180-77cf-11e9-9f81-4781bd0c3ff7.png)

**Comment by jonc125** [comment]
It's happening on scrambler too: https://scrambler.cs.ox.ac.uk/experiments/524/versions/

**Comment by MichaelClerx** [comment]
```
def RunExperiment(
        callbackUrl, signature, modelPath, protoPath, fspecPath, fdataPath,
        tempDir):
    log = logging.getLogger(__name__)
    log.info('RunExperiment called with ' + str(fspecPath) + ' and ' + str(fdataPath))

    try:
        # Tell the website we've started running
        Callback(callbackUrl, signature, {'returntype': 'running'})

        # Call FunctionalCuration exe, writing output to the temporary folder containing inputs
        # (or rather, a subfolder thereof).
        # Also redirect stdout and stderr so we can debug any issues.
        for key, value in config['environment'].iteritems():
            os.environ[key] = value

        raise Exception(str(fspecPath) + ' :: ' + str(fdataPath))
```

Even with this debug code, I _first_ get the exception triggered on the last line, but then very shortly after get a SoftTimeLimitExceeded

**Comment by MichaelClerx** [comment]
Can't promise it's a good idea, but sticking this on line 50 of `tasks.py` in `fc-runner` fixes it:

```
        except (requests.exceptions.RequestException, SoftTimeLimitExceeded) as e:
```

**Comment by jonc125** [comment]
Our code hasn't changed to cause this as far as I can tell, so it must be related to one of security updates we've done for dependencies. The timeout exception shouldn't be raised until several hours after the task starts, so I don't get why it's triggered exactly when the callback is happening. Some bizarre conflict between the requests library and celery perhaps? Anyway, not something I can fix robustly in the next 5 minutes :)

**Comment by jonc125** [comment]
Well, I'm no nearer figuring out root cause here. Rolling back to the older versions of urllib3 and requests doesn't make any difference. I also can't see why the 'running' ping isn't affected but the results send is, unless the fact files are included makes a difference.

Anyway, I think the below patch is a nicer version of your 'fix' @MichaelClerx - at least it doesn't keep trying to send, as the second send will just fail because the experiment is no longer considered running by the front-end...

```diff
diff --git a/fcws/tasks.py b/fcws/tasks.py
index 9626b03..c7d28a8 100644
--- a/fcws/tasks.py
+++ b/fcws/tasks.py
@@ -46,6 +46,10 @@ def Callback(callbackUrl, signature, data, json=False, isRetriedError=False, **k
         try:
             r = requests.post(callbackUrl, verify=False, **kwargs)
             r.raise_for_status()
+        except SoftTimeLimitExceeded:
+            # Just hope we managed to send relevant data!
+            print("Soft time limit thrown while sending callback")
+            break
         except requests.exceptions.RequestException as e:
             print("Error attempting callback at attempt %d: %s" % (attempt + 1, str(e)))
             time.sleep(60 * 2.0**attempt)  # Exponential backoff, in seconds
```

**Comment by MichaelClerx** [comment]
ok!

**Comment by MichaelClerx** [comment]
Should I make a PR for this on `master` @jonc125 ?

**Comment by jonc125** [comment]
Yeah, that'd be good, if you can separate it from the fitting stuff! Thanks.
