### ISSUE TITLE
Improve output from pycml calls in SVN version of Python FC backend

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#161]
```
Constructing protocol_sine_wave.txt
Got RuntimeError: maximum recursion depth exceeded while calling a Python object
Increasing recursion limit to 1500
Importing BasicLibrary.txt as std in protocol_sine_wave.txt
 Constructing BasicLibrary.txt
generating model code...
Traceback (most recent call last):
 File "cardiac.py", line 577, in <module>
   noise_std
 File "cardiac.py", line 319, in createFittingTask
   experiment = FunctionalCurationExperiment(protoFile, modelFile)
 File "/home/celery/eclipse/workspace/Chaste/projects/AidanDaly/modeling/fcexperiment.py", line 21, in __init__
   self.protocol.SetModel(modelFile,exposeNamedParameters=True)
 File "/home/celery/eclipse/workspace/Chaste/projects/FunctionalCuration/src/python/fc/utility/protocol.py", line 408, in SetModel
   print subprocess.check_output(code_gen_cmd, stderr=subprocess.STDOUT)
 File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
   raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['./python/pycml/translate.py', '-t', 'Cython', '-p', '--Wu', '--protocol=/tmp/tmpVPcbWU/tmpRJ4OFG.xml', '/tmp/tmp5_6ZjP/model/model_1_wang_sobie_cell.cellml', '-c', 'GeneratedModel', '-o', '/tmp/tmpVPcbWU/model.pyx', '--expose-named-parameters']' returned non-zero exit status 1
```

Happens if model or protocol is not perfect. Should be updated in the chaste projects SVN to also show what the actual pycml output is

**Comment by jonc125** [comment]
Yeah, that sucks. But given we're supposed to be retiring pycml I'm not inclined to work on it!

At least for the protocol there's now a syntax check that runs when you add a new version, so you see syntax errors there before running any experiments.

**Comment by MichaelClerx** [comment]
I think this will come up in the workshop!

**Comment by MichaelClerx** [comment]
Something like this help:

```
            try:
                print subprocess.check_output(code_gen_cmd, stderr=subprocess.STDOUT)
            except:
                print subprocess.call(code_gen_cmd, stderr=subprocess.STDOUT)
                raise
```

On line 408 of protocol.py

I don't have svn rights for the chaste project

**Comment by jonc125** [comment]
This is a better fix I think:
```diff
diff --git c/src/python/fc/utility/protocol.py w/src/python/fc/utility/protocol.py
index 5087f49..2894547 100644
--- c/src/python/fc/utility/protocol.py
+++ w/src/python/fc/utility/protocol.py
@@ -404,13 +404,24 @@ class Protocol(object):
             # Generate the (protocol-modified) model code
             class_name = 'GeneratedModel'
             code_gen_cmd = self.GetConversionCommand(model, xml_file, class_name, temp_dir,
-                                                     useCython=useCython, useNumba=useNumba, exposeNamedParameters=exposeNamedParameters)
-            print subprocess.check_output(code_gen_cmd, stderr=subprocess.STDOUT)
+                                                     useCython=useCython, useNumba=useNumba,
+                                                     exposeNamedParameters=exposeNamedParameters)
+            try:
+                print subprocess.check_output(code_gen_cmd, stderr=subprocess.STDOUT)
+            except subprocess.CalledProcessError as e:
+                print e.output
+                raise
             if useCython:
                 # Compile the extension module
-                print subprocess.check_output(['python', 'setup.py', 'build_ext', '--inplace'], cwd=temp_dir, stderr=subprocess.STDOUT)
+                try:
+                    print subprocess.check_output(['python', 'setup.py', 'build_ext', '--inplace'],
+                                                  cwd=temp_dir, stderr=subprocess.STDOUT)
+                except subprocess.CalledProcessError as e:
+                    print e.output
+                    raise
             # Create an instance of the model
             self.modelPath = temp_dir
```

**Comment by MichaelClerx** [comment]
Cool! How do we get it in there?

**Comment by jonc125** [comment]
I've just logged in to my account on muck and committed from there!

**Comment by MichaelClerx** [comment]
Great! That's updated it on my VM after a `vagrant provision`
