### ISSUE TITLE
PyCML error?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/WebLab#163]
```
celery@weblab:~/eclipse/workspace/Chaste/python/pycml$ python translate.py ../../projects/AidanDaly/data-2-workshop/model_3_wang_1997_ikr.cellml 
Traceback (most recent call last):
  File "translate.py", line 55, in <module>
    translators.run()
  File "/home/celery/eclipse/workspace/Chaste/python/pycml/translators.py", line 6798, in run
    config.finalize_config()
  File "/home/celery/eclipse/workspace/Chaste/python/pycml/translators.py", line 5955, in finalize_config
    self.find_current_vars()
  File "/home/celery/eclipse/workspace/Chaste/python/pycml/translators.py", line 6269, in find_current_vars
    if self.i_stim_var.get_type() == VarTypes.Mapped:
AttributeError: 'list' object has no attribute 'get_type'
```

Seems a valid model. Know we're not maintaining this but happens with fitting prototype...

**Comment by MichaelClerx** [comment]
Worked around it
