### ISSUE TITLE
Experiments that should be grey for missing metadata terms are coming up red now

### ISSUE THREAD

**Issue by mirams** [ModellingWebLab/WebLab#404]
e.g. this one
<img width="894" alt="image" src="https://user-images.githubusercontent.com/858776/159690375-7065255e-0b18-44a8-89b3-995aa87299e0.png">

became this on re-running the experiment (and changes from grey to red in the matrix accordingly):
<img width="962" alt="image" src="https://user-images.githubusercontent.com/858776/159690460-d4495e44-825a-4f46-8111-ce7695683791.png">

with an error like this in the std::out:
```
Traceback (most recent call last):
  File "/home/celery/eclipse/workspace/Chaste/python/pycml/translate.py", line 55, in <module>
    translators.run()
  File "/home/celery/eclipse/workspace/Chaste/python/pycml/translators.py", line 6789, in run
    protocol.apply_protocol_file(doc, options.protocol)
  File "/home/celery/eclipse/workspace/Chaste/python/pycml/protocol.py", line 1507, in apply_protocol_file
    Protocol.apply_protocol_file(doc, proto_file_path)
  File "/home/celery/eclipse/workspace/Chaste/python/pycml/protocol.py", line 91, in apply_protocol_file
    proto.modify_model()
  File "/home/celery/eclipse/workspace/Chaste/python/pycml/protocol.py", line 593, in modify_model
    self._check_equation_lhs(input) # Create LHS var if needed
  File "/home/celery/eclipse/workspace/Chaste/python/pycml/protocol.py", line 681, in _check_equation_lhs
    raise ProtocolError("Variable %s on the LHS of a 'define' does not exist in the model and is not an output with units or optional." % vname)
protocol.ProtocolError: Variable oxmeta:membrane_fast_transient_outward_current_conductance on the LHS of a 'define' does not exist in the model and is not an output with units or optional.
/home/celery/eclipse/workspace/Chaste/python/pycml/translate.py /home/celery/eclipse/workspace/Chaste/projects/FunctionalCuration/dynamic/tmp_32943_1648035196/ohara_rudy_cipa_v1_2017.cellml -A -p --expose-annotated-variables --protocol=/tmp/fc_webservice_testoutput/ProtocolConverter/tmp3TBoPS.xml --conf=/home/celery/eclipse/workspace/Chaste/python/pycml/config.xml --use-chaste-stimulus --convert-interfaces --warn-on-unit-conversions --Wu --conf=/tmp/tmpEspvz0.xml -y -t CVODE -c Dynamicohara_rudy_cipa_v1_2017FromCellMLCvode -o /home/celery/eclipse/workspace/Chaste/projects/FunctionalCuration/build/optimised/dynamic/tmp_32943_1648035196/ohara_rudy_cipa_v1_2017.cpp
scons: *** [projects/FunctionalCuration/build/optimised/dynamic/tmp_32943_1648035196/ohara_rudy_cipa_v1_2017.cpp] Error 1
scons: building terminated because of errors.
```
we did discuss this at some point but I couldn't find an issue so started a new one. @jonc125 @MauriceHendrix @MichaelClerx does anyone know what change caused this?

**Comment by MauriceHendrix** [comment]
I don't really know anything about this, but I do know I haven't tocuhed this part of the system

**Comment by mirams** [comment]
I think you are probably right Maurice, this one has been going on for a few months, most of the red ones that should be grey were run in October 2021, so if you didn't change anything before then you are off the hook!

**Comment by jonc125** [comment]
I suspect this originates from when we switched from pycml to weblab-fc for determining compatibility…

**Comment by mirams** [comment]
Did it ever work then Jon? Or was it put in broken!?

**Comment by mirams** [comment]
Added @kwabenantim , see above, Jon thinks this is to do with no longer using PyCML for something!

**Comment by jonc125** [comment]
https://github.com/ModellingWebLab/WebLab/blob/master/weblab/experiments/processing.py#L48 should be deciding `Runnable.STATUS_INAPPLICABLE` for such combinations but clearly isn't.

The code that does the check is https://github.com/ModellingWebLab/fc-runner/blob/master/fcws/tasks.py#L168 which calls https://github.com/ModellingWebLab/fc-runner/blob/master/fcws/utils.py#L84 which now uses https://github.com/ModellingWebLab/weblab-fc/blob/master/fc/protocol.py#L750. Which implies that https://github.com/ModellingWebLab/weblab-fc/blob/master/fc/protocol.py#L677 isn't listing everything it should as a required term...
